changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Bug Fix 🐞
      labels:
        - bug-fix
    - title: New Features 🎉
      labels:
        - feature
    - title: Other Changes
      labels:
        - "*"